---
abstract: 'RT-Extension-Realtime Extension'
author:
  - 'Best Practical Solutions, LLC <craig@kaiserengineering.io>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Realtime
no_index:
  directory:
    - html
    - inc
    - static
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/craigkai/rt-extension-realtime
version: '0.01'
x_module_install_rtx_version: '0.43'
x_requires_rt: 4.4.0
x_rt_too_new: 5.2.0
